### ISSUE TITLE
Bug: longest miss streak difference displayed wrong

### ISSUE THREAD

**Issue by maggaou** [Timmeey86/CustomTrainingStatisticsPlugin#46]
I haven't used the plugin much so I don't know if the issue is persistent.

Session one: my longest miss streak is 7
Session two: my longest miss streak is 4. Issue: difference to session one is displayed as +3 but it should be -3.

**Comment by Timmeey86** [comment]
This is actually half-way intentional. It basically means "3 better than the last run", and in this case, lower is better. 

I know it can be confusing, but it's supposed to be +/green = good, -/red = bad, that way colorblind people will have the +/- as a fallback to see quickly whether they improved or not

**Comment by maggaou** [comment]
I personally would prefer green minus sign even after reading your answer. But I will gladly respect the author's design view.

I appreciate all your time you have put into this fantastic plugin.

**Comment by Timmeey86** [comment]
I appreciate your feedback. I will close this issue, but don't hesitate reporting anything else which seems off for you
