### ISSUE TITLE
Feature: show training pack name and code in the statistics summary menu

### ISSUE THREAD

**Issue by maggaou** [Timmeey86/CustomTrainingStatisticsPlugin#50]
This is a feature that may not be essential to this plugin. In the following I present some use case.

The feature may be useful when seeking and trying new training packs. Currently there is one implementation that loads training packs automatically from a website (https://bakkesplugins.com/plugins/view/309). It's a closed source plugin so exploration is currently limited to one webpage. In the future we hope to see better possibilities to explore training packs. While discovering I could use the stats summary menu to get the name and code of the training pack. Why would I have to use different menu to do that? The summary menu should allow to copy the code to clipboard. There are plugins that make use of the clipboard (https://bakkesplugins.com/plugins/view/179).

**Comment by Timmeey86** [comment]
The upcoming version will be able to export both meta information (Training Pack Name, Code and Author) and statistics to TSV (tab separated values). It will do the export in a way which allows seemless import to Excel by formatting the numbers in accordance with the user's regional settings (Some regions would write "3,47" instead of "3.47" so a comma separated list would cause problems in those regions).
This implements both this issue and #51
