### ISSUE TITLE
Feature: branding

### ISSUE THREAD

**Issue by maggaou** [Timmeey86/CustomTrainingStatisticsPlugin#71]
Include some text in the stat overlay that includes the name of the plugin etc. 

Example: Custom Training Statistics - A plugin for BakkesMod

It could be located at the bottom.

There are number of reasons for branding and I have many personal views on that but I just give one practical example.

Player uses this plugin and shares a screenshot in some big community. Now this screenshot contains references to this plugin and BakkesMod in general. Result: BakkesMod and this plugin will expand their userbase. More users potentially means also more pull requests.

**Comment by Timmeey86** [comment]
I added the plugin name and version for now - This will also make bug tracking easier, since sometimes it's important for me to know which version the user had the issue with. I guess if they google the plugin name, they will find out about Bakkesmod anyway so I decided to not add more text to the display
